#!/usr/bin/python3
import sys
import math

def factorial_number (number):
    for i in range (2, int(math.sqrt(number))+1):
        if number % i == 0:
            return f"{number}= {i} * {number // i}"

def factorial_file(file_path):
    with open (file_path, 'r') as file:
        numbers = file.read().splitlines()
        for number in numbers:
            print(factorial_number(int(number)))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    factorial_file(file_path)    
